services:
  postgres:
    image: postgres:16

    container_name: colore-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: colore
      POSTGRES_PASSWORD: colore
      POSTGRES_DB: colore

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: